.. _pars_outlierdetectionspecstep_reffile:

PARS-OUTLIERDETECTIONSPECSTEP Parameter Reference File
------------------------------------------------------

:REFTYPE: PARS-OUTLIERDETECTIONSPECSTEP
:Data model: N/A

Reference Selection Keywords
++++++++++++++++++++++++++++
CRDS selects appropriate pars-outlierdetectionstep references based on the following keywords.

========== ====================================
Instrument Keywords
========== ====================================
FGS        EXP_TYPE
MIRI       EXP_TYPE, FILTER, SUBARRAY, TSOVISIT
NIRCAM     EXP_TYPE, FILTER, PUPIL, TSOVISIT
NIRISS     EXP_TYPE, FILTER, PUPIL, TSOVISIT
========== ====================================

.. include:: ../includes/standard_keywords.inc
