.. _pars_outlierdetectionifustep_reffile:

PARS-OUTLIERDETECTIONIFUSTEP Parameter Reference File
-----------------------------------------------------

:REFTYPE: PARS-OUTLIERDETECTIONIFUSTEP
:Data model: N/A

Reference Selection Keywords
++++++++++++++++++++++++++++
CRDS selects appropriate pars-outlierdetectionstep references based on the following keywords.

========== ====================================
Instrument Keywords
========== ====================================
FGS        EXP_TYPE
MIRI       EXP_TYPE, FILTER, SUBARRAY, TSOVISIT
NIRCAM     EXP_TYPE, FILTER, PUPIL, TSOVISIT
NIRISS     EXP_TYPE, FILTER, PUPIL, TSOVISIT
========== ====================================

.. include:: ../includes/standard_keywords.inc
